export const actionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SET_LIMITED_PRODUCTS: "SET_LIMITED_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
	SET_CATEGORIES: "SET_CATEGORIES",
	DARK_MODE: "DARK_MODE",
	SET_SELECTEDCATEGORY: "SET_SELECTEDCATEGORY",
	SET_FAVORITE_PRODUCTS: "SET_FAVORITE_PRODUCTS",
};
